In [ ]:
# Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
#Load Dataset
import pandas as pd

df = pd.read_csv(
    "Amazon_Product_Reviews.csv",
    engine='python',
    on_bad_lines='skip',
    quoting=3   # VERY IMPORTANT 🔥
)

df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1.0,1.0,5.0,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0.0,0.0,1.0,1346976000,Not as Advertised,"""Product arrived labeled as Jumbo Salted Peanu..."
2,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3.0,3.0,2.0,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
3,9,B000E7L2R4,A1MZYO9TZK0BBI,R. James,1.0,1.0,5.0,1322006400,Yay Barley,Right now I'm mostly just sprouting this so my...
4,10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0.0,0.0,5.0,1351209600,Healthy Dog Food,This is a very healthy dog food. Good for thei...

In [ ]:
#Data Preprocessing
# Select required columns
df = df[['Text', 'Score']]

# Remove null values
df = df.dropna()

# Convert Score to sentiment
# 1 = Positive, 0 = Negative
df['sentiment'] = df['Score'].apply(lambda x: 1 if x >= 4 else 0)

df.head()

                                                Text  Score  sentiment
0  I have bought several of the Vitality canned d...    5.0          1
1  "Product arrived labeled as Jumbo Salted Peanu...    1.0          0
2  If you are looking for the secret ingredient i...    2.0          0
3  Right now I'm mostly just sprouting this so my...    5.0          1
4  This is a very healthy dog food. Good for thei...    5.0          1

In [ ]:
#Feature Selection
X = df['Text']
y = df['sentiment']

In [ ]:
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
#Convert Text → Numbers (TF-IDF)
vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [ ]:
#Model Training
model = LogisticRegression()

model.fit(X_train_vec, y_train)

LogisticRegression()

In [ ]:
#Prediction
y_pred = model.predict(X_test_vec)

In [ ]:
#Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.8937790943715616

Classification Report:

              precision    recall  f1-score   support

           0       0.89      0.47      0.62       428
           1       0.89      0.99      0.94      1935

    accuracy                           0.89      2363
   macro avg       0.89      0.73      0.78      2363
weighted avg       0.89      0.89      0.88      2363